### ISSUE TITLE
Add NPM support

### ISSUE THREAD

**Issue by mlewis-everley** [heyesr/rgraph#23]
Hi, I have used this library on and off for quite a few years and it has been super helpful! I was just wondering if you have considered adding package info so it can be installed via NPM/Yarn?

Thanks for all the great work!

Mo

**Comment by heyesr** [comment]
Hi Mo,

I've never used or looked at npm so I'm afraid not. If it's of any use you could use the cdnJS hosted versions of the libraries which are linked to on the download page:

https://www.rgraph.net/download.html#view-the-source-code-of-the-rgraph-files

That way you don't need to maintain the RGraph files locally. For example

Minified:
https://cdnjs.cloudflare.com/ajax/libs/RGraph/6.12/RGraph.svg.common.core.min.js

Original:
https://cdnjs.cloudflare.com/ajax/libs/RGraph/6.12/RGraph.svg.common.core.js

HTH

**Comment by mlewis-everley** [comment]
Thanks for the reply, I am aware of the CDN versions, but I generally use webpack to transpile all the assets into a single minified library (or several if the filesize gets too large).

At the moment I have downloaded the libs and included them manually, but installation via a package manager is always a nicer workflow.
